# Generated by Django 5.0.6 on 2025-05-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('episode_count', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('upcoming', 'Upcoming')], default='ongoing', max_length=20)),
                ('average_rating', models.FloatField(default=0)),
                ('is_public_api', models.BooleanField(default=False)),
                ('public_api_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
