# Generated by Django 5.0.6 on 2025-05-30 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_genre_anime_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='average_rating',
        ),
    ]
